<a href="https://colab.research.google.com/github/maushamkumar/NumPy/blob/main/NumPy_Trick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.sort
Return a sorted copy of an array

In [1]:
# Code
import numpy as np
a = np.random.randint(1, 100, 15)
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [2]:
np.sort(a)

array([12, 14, 17, 26, 30, 48, 51, 66, 69, 73, 75, 82, 83, 94, 94])

In [3]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[68, 73, 95, 89],
       [ 1, 91, 87, 49],
       [18, 16, 11, 11],
       [98, 21, 15, 14],
       [96,  8, 50,  3],
       [17, 21, 66, 90]])

In [5]:
np.sort(b, axis=0)

array([[ 1,  8, 11,  3],
       [17, 16, 15, 11],
       [18, 21, 50, 14],
       [68, 21, 66, 49],
       [96, 73, 87, 89],
       [98, 91, 95, 90]])

In [6]:
np.sort(a)[::-1]

array([94, 94, 83, 82, 75, 73, 69, 66, 51, 48, 30, 26, 17, 14, 12])

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array.

In [8]:
# code
# This append function is similar to Python append function
a
np.append(a, 100)

array([ 94,  30,  82,  75,  14,  83,  51,  17,  12,  66,  26,  69,  94,
        48,  73, 100])

In [9]:
b

array([[68, 73, 95, 89],
       [ 1, 91, 87, 49],
       [18, 16, 11, 11],
       [98, 21, 15, 14],
       [96,  8, 50,  3],
       [17, 21, 66, 90]])

In [12]:
np.append(b, np.ones((b.shape[0], 1)),axis=1)

array([[68., 73., 95., 89.,  1.],
       [ 1., 91., 87., 49.,  1.],
       [18., 16., 11., 11.,  1.],
       [98., 21., 15., 14.,  1.],
       [96.,  8., 50.,  3.,  1.],
       [17., 21., 66., 90.,  1.]])

# np.concatenate
numpy.concatenate() fucntion concatenate a sequence of arrays along an existing axis.

In [13]:
# code
# Generally we use np.concatenate with tabular data to concatenate data
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
# Row base
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
# Coloumn wise concatenation
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
with the help of np.unique() method, we can get the unique values from an array given as a parameter in np.unique() method.

In [16]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
with the help of numpy.expand_dims, we can get the expanded dimensions of an array

In [17]:
# code
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [18]:
np.expand_dims(a, axis=0)

array([[94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73]])

In [19]:
np.expand_dims(a, axis=1)

array([[94],
       [30],
       [82],
       [75],
       [14],
       [83],
       [51],
       [17],
       [12],
       [66],
       [26],
       [69],
       [94],
       [48],
       [73]])

# np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [20]:
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [21]:
# Find all the indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  5,  6,  9, 11, 12, 14]),)

In [22]:
# replace all value > 50 with 0
# np.where(condition, true, false)
np.where(a>50, 0, a)

array([ 0, 30,  0,  0, 14,  0,  0, 17, 12,  0, 26,  0,  0, 48,  0])

# np.argmax
The numpy.argmax() function returns the indices of the max element of the array in a particular axis.

In [23]:
# code
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [24]:
np.argmax(a)

0

In [25]:
b

array([[68, 73, 95, 89],
       [ 1, 91, 87, 49],
       [18, 16, 11, 11],
       [98, 21, 15, 14],
       [96,  8, 50,  3],
       [17, 21, 66, 90]])

In [27]:
np.argmax(b, axis=0)

array([3, 1, 0, 5])

In [28]:
np.argmax(b, axis=1)

array([2, 1, 0, 0, 0, 3])

In [29]:
# np.agrmin
np.argmin(a)

8

# np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [30]:
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [31]:
np.cumsum(a)

array([ 94, 124, 206, 281, 295, 378, 429, 446, 458, 524, 550, 619, 713,
       761, 834])

In [32]:
b

array([[68, 73, 95, 89],
       [ 1, 91, 87, 49],
       [18, 16, 11, 11],
       [98, 21, 15, 14],
       [96,  8, 50,  3],
       [17, 21, 66, 90]])

In [33]:
np.cumsum(b)

array([  68,  141,  236,  325,  326,  417,  504,  553,  571,  587,  598,
        609,  707,  728,  743,  757,  853,  861,  911,  914,  931,  952,
       1018, 1108])

In [34]:
np.cumsum(b, axis=0)

array([[ 68,  73,  95,  89],
       [ 69, 164, 182, 138],
       [ 87, 180, 193, 149],
       [185, 201, 208, 163],
       [281, 209, 258, 166],
       [298, 230, 324, 256]])

In [35]:
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [36]:
# np.cumprod
np.cumprod(a)

array([                  94,                 2820,               231240,
                   17343000,            242802000,          20152566000,
              1027780866000,       17472274722000,      209667296664000,
          13838041579824000,   359789081075424000,  6378702520494704384,
       -9144517505912991232,  3785017485205659648,  -394884685630119936])

# np.percentile
numpy.percentile() function used to compute the nth percentile of the given data(arrary elements) along with specified axis.

In [37]:
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [38]:
np.percentile(a, 100)

94.0

In [39]:
np.percentile(a, 0)

12.0

In [41]:
np.percentile(a, 50)

66.0

# np.histogram
numpy has a built-in numpy.histogram function which represents the frequency of data distribution in the graphical form

In [42]:
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [44]:
np.histogram(a, bins=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([3, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
Return Pearson product-moment correlation coefficients.

In [45]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

In [46]:
np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin
With the help of numpy.isin() mehtod. we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [47]:
# code
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [50]:
items = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
a[np.isin(a, items)]

array([30])

# np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [51]:
# code
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [52]:
np.flip(a)

array([73, 48, 94, 69, 26, 66, 12, 17, 51, 83, 14, 75, 82, 30, 94])

# np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [53]:
# code
a

array([94, 30, 82, 75, 14, 83, 51, 17, 12, 66, 26, 69, 94, 48, 73])

In [54]:
np.put(a, [1, 3], [110, 530])

# np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [55]:
# code
a

array([ 94, 110,  82, 530,  14,  83,  51,  17,  12,  66,  26,  69,  94,
        48,  73])

In [56]:
np.delete(a, [0])

array([110,  82, 530,  14,  83,  51,  17,  12,  66,  26,  69,  94,  48,
        73])

In [57]:
np.delete(a, [1, 4, 7])

array([ 94,  82, 530,  83,  51,  12,  66,  26,  69,  94,  48,  73])

# Set functions
* np.union 1D
* np.intersect 1D
* np.setdiff 1D
* np.setxor 1D
* np.in 1D


In [58]:
m = np.array([1, 2,3 , 4, 5])
n = np.array([3,4, 5, 6, 7])

In [61]:
np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
np.setdiff1d(m, n)

array([1, 2])

In [64]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [65]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

# np.clip
numpy.clip() function is used to clip(limit) the values in an array.


In [66]:
# code
a

array([ 94, 110,  82, 530,  14,  83,  51,  17,  12,  66,  26,  69,  94,
        48,  73])

In [68]:
np.clip(a, a_min=10, a_max=85)

array([85, 85, 82, 85, 14, 83, 51, 17, 12, 66, 26, 69, 85, 48, 73])