<a href="https://colab.research.google.com/github/maushamkumar/NumPy/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
arr = np.arange(10)
arr[4] = 1
arr

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here
a = int(input("Enter the number of rows: "))
b = int(input("Enter the number of columns: "))
arr = np.arange(a*b).reshape(a,b)
arr

Enter the number of rows: 2
Enter the number of columns: 2


array([[0, 1],
       [2, 3]])

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [6]:
#Code here
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [7]:
#Code here
arr = np.linspace(0, 1, 11, endpoint=False)[1:]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [9]:
#Code here
arr = np.eye(4, 4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [12]:
#Code here
arr = np.zeros((5, 5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [13]:
#code here
arr = np.random.randint(1, 100, size=(10, 2))
point = np.array([2, 3])
distance = np.sqrt(np.sum((arr - point) ** 2, axis=1))
distance

array([ 49.51767361,  63.28506933,  54.64430437,  86.53323061,
        60.92618485,  72.20110802, 103.8701112 ,  63.78087488,
        53.74011537,  36.40054945])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [15]:
#Code here
a = np.zeros(shape=(6, 7, 8))
np.unravel_index(100, a.shape)

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [17]:
#Code here
arr = np.array([1, 2, 3, 4, -8, -10])
arr[::-1]

arr = input().strip().split()
arr = np.array(arr, dtype=float)[::-1]
arr

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [18]:
#Code here
arr = np.array([])
print("elements_count : ", arr.size)

elements_count :  0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [19]:
#Code here
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [27]:
#Coder here
a = np.array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

c= np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

np.vstack((a, b,c))

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [28]:
#Code here
import numpy as np
import datetime

def date_array(start_date, end_date):
    # Check if the inputs are exactly two strings
    if not (isinstance(start_date, str) and isinstance(end_date, str)):
        raise ValueError("Both start_date and end_date must be strings")

    # Convert strings to date objects
    try:
        start_date_obj = datetime.datetime.strptime(start_date, '%Y-%m-%d').date()
        end_date_obj = datetime.datetime.strptime(end_date, '%Y-%m-%d').date()
    except ValueError:
        raise ValueError("Date format should be YYYY-MM-DD")

    # Ensure dates are within the same year
    if start_date_obj.year != end_date_obj.year:
        raise ValueError("Dates must be within the same year")

    # Generate date range
    num_days = (end_date_obj - start_date_obj).days + 1
    date_range = [start_date_obj + datetime.timedelta(days=i) for i in range(num_days)]

    # Convert to numpy array
    date_array = np.array(date_range, dtype='datetime64[D]')

    return date_array

# Example usage
start = '2022-12-06'
end = '2022-12-10'
print(date_array(start, end))


['2022-12-06' '2022-12-07' '2022-12-08' '2022-12-09' '2022-12-10']


###`Q-14:` Subtract the mean of each row from a matrix.

In [31]:
#code here
arr = np.random.randint(1, 100, size=(4, 4))
a = arr.mean()
print(arr )
print(a)
arr - a

[[18  8 26 71]
 [16 64 15 57]
 [28 76  2 56]
 [60 31 87 56]]
41.9375


array([[-23.9375, -33.9375, -15.9375,  29.0625],
       [-25.9375,  22.0625, -26.9375,  15.0625],
       [-13.9375,  34.0625, -39.9375,  14.0625],
       [ 18.0625, -10.9375,  45.0625,  14.0625]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

In [39]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

array[:, [0, 1]] = array[:, [1, 0]]
array

array([[ 2,  1,  3,  4],
       [ 6,  5,  7,  8],
       [10,  9, 11, 12],
       [14, 13, 15, 16]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

In [40]:
arr = np.arange(10).reshape(2, 5)
arr[arr % 2 == 1] = -1
arr

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [41]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a, b)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [51]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3163, 8338, 9757, 2427, 1703],
       [3508, 2844, 7205, 7986, 9567],
       [9208, 2065, 1699,  237, 1081],
       [ 260, 6107, 2753, 6806, 7962],
       [5017, 8575, 8091, 5324, 7165],
       [7662, 8290,  316, 1396, 8669],
       [9685, 9996,  122, 9801, 7223],
       [ 834, 3508, 9010,  506, 1375]])

In [53]:
#Code here
x = (arr1 - arr1.min())/ (arr1.max() - arr1.min())
x

array([[0.30798055, 0.83208426, 0.97579502, 0.23344136, 0.16011748],
       [0.3429208 , 0.27567349, 0.71733846, 0.79643508, 0.95655256],
       [0.92019445, 0.19677942, 0.15971238, 0.01164675, 0.09712376],
       [0.0139761 , 0.60613733, 0.26645736, 0.67692931, 0.79400446],
       [0.4957464 , 0.85608669, 0.80706907, 0.52683816, 0.71328742],
       [0.76362163, 0.82722301, 0.01964756, 0.12902572, 0.86560664],
       [0.96850314, 1.        , 0.        , 0.98025116, 0.71916143],
       [0.07210857, 0.3429208 , 0.90014179, 0.03889001, 0.12689893]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def nth_largest(arr, n):
    sorted_arr = np.sort(arr)
    return sorted_arr[-n]

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [56]:
#code here
a = np.array([1,2,3])
repeat = np.repeat(a, 3)
tiled = np.tile(a, 3)
np.concatenate((repeat, tiled))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])